codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "10...50"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        # Lower coverage target for now as we're only using mocked tests
        target: 15%
    patch:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main

ignore:
  - "tests/**/*"
  - "**/*.spec.js"
  - "**/*.test.js"
  - "**/*.vitest.js"
  - "**/types/**"