PREFIX ragno: <http://purl.org/stuff/ragno/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX semem: <http://purl.org/semem/>

SELECT ?textElement ?content ?sourceUnit {
  GRAPH <${graphURI}> {
    ?textElement a ragno:TextElement ;
                 ragno:content ?content .
    OPTIONAL { ?textElement prov:wasDerivedFrom ?sourceUnit }
    
    FILTER NOT EXISTS {
      ?textElement semem:hasChunks true .
    }
    
    FILTER (STRLEN(?content) > ${minContentLength})
  }
}
LIMIT ${limit}