PREFIX ragno: <http://purl.org/stuff/ragno/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX semem: <http://semem.hyperdata.it/>
PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE WHERE {
    GRAPH <${graphURI}> {
        ?unit a ragno:Unit ;
              semem:sourceFile "${sourceFile}" ;
              ?p ?o .
        
        ?textElement ragno:hasTextElement ?unit ;
                     ?tp ?to .
        
        ?chunk prov:wasDerivedFrom ?textElement ;
               ?cp ?co .
        
        ?corpuscle prov:wasDerivedFrom ?chunk ;
                   ?cpp ?cpo .
    }
}