PREFIX ragno: <http://purl.org/stuff/ragno/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX olo: <http://purl.org/ontology/olo/core#>
PREFIX semem: <http://semem.hyperdata.it/>

INSERT DATA {
  GRAPH <${graphURI}> {
    # Mark the TextElement as having chunks
    <${textElementURI}> semem:hasChunks true .
    
    # Create the ordered list for chunks
    <${chunkListURI}> a olo:OrderedList ;
                      olo:length ${chunkCount} ;
                      dcterms:title "Chunks for ${textElementTitle}" ;
                      prov:wasDerivedFrom <${textElementURI}> .
    
    # Associate the ordered list with the TextElement
    <${textElementURI}> semem:hasChunkList <${chunkListURI}> .
    
    ${chunkTriples}
    
    ${slotTriples}
  }
}