PREFIX ragno: <http://purl.org/stuff/ragno/>
PREFIX semem: <http://purl.org/stuff/semem/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
    GRAPH <{{graphName}}> {
        <{{id}}> a ragno:Entity ;
            ragno:content """{{content}}""" ;
            ragno:subType semem:{{type}} ;
            ragno:isEntryPoint false ;
            semem:processingStatus "lazy" ;
            dcterms:created "{{timestamp}}"^^xsd:dateTime {{titleStatement}} {{metadataStatements}} .
    }
}