PREFIX ragno: <http://purl.org/stuff/ragno/>
PREFIX semem: <http://purl.org/stuff/semem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
    GRAPH <{{graphName}}> {
        {{elementUri}} semem:processingStatus "lazy" ;
                      ragno:isEntryPoint false .
    }
}
INSERT {
    GRAPH <{{graphName}}> {
        {{elementUri}} semem:processingStatus "processed" ;
                      ragno:isEntryPoint true ;
                      ragno:embedding "{{embedding}}" .
        {{conceptStatements}}
    }
}
WHERE {
    GRAPH <{{graphName}}> {
        {{elementUri}} semem:processingStatus "lazy" .
    }
}